friends/config/routes.rb
Rails.application.routes.draw do
  get 'dbz/divide'
  get 'ps1/web'
  resources :friends
  #get 'home/index'
  root 'home#index'
end

friends/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

friends/app/models/friend.rb
class Friend < ApplicationRecord
    
end

friends/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

friends/app/controllers/dbz_controller.rb
class DbzController < ApplicationController
  def divide
  	logger.error "About to divide by 0\n"
    	@number = 4/0
  end
end

friends/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.page(params[:page])
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:name, :email, :phoneno)
    end
end

friends/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

friends/app/controllers/ps1_controller.rb
class Ps1Controller < ApplicationController
  require 'open-uri'
  require 'nokogiri'
  
  def web
  	html=URI.open("https://www.nytimes.com")
  	doc = Nokogiri::HTML(html)
    	news=[]
    	
    	doc.css('a.css-azmf6i').each do |world|
    		a_url=world["href"]
    		
    		a_heading=world.css('h3.e1lsht870').text
    		if !a_heading.empty?
    			if a_url.include? "world" and a_url.include? "nytimes.com"
    				single_news={ "heading" => world.css('h3.e1lsht870').text,
    					"url" => a_url
    					}
    				news.push(single_news)
    			end
    			
    		end
    	end
    	@result=news
    	
    	
    	
    	
    	html1=URI.open("https://www.thehindu.com/news/international/")
  	doc1 = Nokogiri::HTML(html1)
  	
  	
    	
    	
    	
    	
    	
    	hindu_news=[]
    	hindu_all_links=doc1.css('h2 a')
    	hindu_all_links.each do |wor|
    		
    		hindu_url=wor["href"]
    		
    		
    		hindu_heading=wor.text 
    		
    		if !hindu_heading.empty?
    			if hindu_url.include? "international" and hindu_url.include? "news"
    				shindu_news={ "heading" => hindu_heading,
    					"url" =>  hindu_url
    						}
    				hindu_news.push(shindu_news)
    			end
    		end
    		
    	end
    	
    	
    	
    	
    	@result2=hindu_news
    	
    	
    	
  end
  
  
  
  
  
  
end

friends/app/helpers/application_helper.rb
module ApplicationHelper
end

friends/app/helpers/dbz_helper.rb
module DbzHelper
end

friends/app/helpers/friends_helper.rb
module FriendsHelper
end

friends/app/helpers/home_helper.rb
module HomeHelper
end

friends/app/helpers/ps1_helper.rb
module Ps1Helper
end

friends/app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", placeholder: "name" %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control",  placeholder: "email" %>
  </div>

  <div class="field">
    <%= form.label :phoneno %>
    <%= form.text_field :phoneno, class: "form-control", placeholder: "phone no" %>
  </div>
  
  </br>

  <div class="actions">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

friends/app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

friends/app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friends List</h1>

<table class="table table-striped table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phoneno</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phoneno %></td>
        <td><%= link_to 'Show', friend %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
        <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @friends, :window => 2%>
<%= link_to 'New Friend', new_friend_path , class: "btn btn-secondary" %>

friends/app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path %>

friends/app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @friend.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @friend.email %>
</p>

<p>
  <strong>Phoneno:</strong>
  <%= @friend.phoneno %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>

friends/app/views/ps1/web.html.erb
<%= link_to 'divide by Zero', dbz_divide_path , class: "btn btn-secondary" %>


</br>
	<h1> World News from New York times </h1>
</br>
 

<table style="text-align: center" class="table table-striped table-bordered">
<thead class="table-dark">
    <tr>
      <th>Heading</th>
      <th>Link</th>
    </tr>
  </thead>
  <% @result.each do |result| %>
	
	<tr>
		<td> <%= result["heading"] %> </td>
		<td> <a href="<%= result["url"] %>" > Read more about this article </a> </td>
	</tr>
	
  <% end %>

</table>
</br>

</br>
 <h1> International news from The Hindu </h1>
 </br>
 
 <table style="text-align: center" class="table table-striped table-bordered">
<thead class="table-dark">
    <tr>
      <th>Heading</th>
      <th>Link</th>
    </tr>
  </thead>
  <% @result2.each do |result2| %>
	
	<tr>
		<td> <%= result2["heading"] %> </td>
		<td> <a href="<%= result2["url"] %>" > Read more about this article </a> </td>
	</tr>
	
  <% end %>

</table>


</br>
</br>